### ISSUE TITLE
Fix the as_conversion lints issue.

### ISSUE THREAD

**Issue by MrWWheat** [datenlord/datenlord#105]
The lint error is: `Using a potentially dangerous silent 'as' conversion`. 

The solution is to implement the [`from` trait](https://doc.rust-lang.org/std/convert/trait.From.html). Then using `from` trait rather than as conversion.

**Comment by Reto911** [comment]
Now, all `as_conversion`s are presented in file `src/async_fuse/util.rs`, and those usages are guarenteed to be safe.
