### ISSUE TITLE
Complie failed with grpcio-sys

### ISSUE THREAD

**Issue by genedna** [datenlord/datenlord#221]
When I complied the datenlrod with `cargo build`, I got error within the process:

```
error: failed to run custom build command for `grpcio-sys v0.8.1`
```

And more output:

```
  --- stderr
  CMake Warning at cmake/protobuf.cmake:51 (message):
    gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
  Call Stack (most recent call first):
    CMakeLists.txt:254 (include)


  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS
```

**Desktop:**
 - OS: Ubuntu 21.04
 - CPU Arch: amd64
 - Kernel Version: 5.11.0-25-generic
 - Protoc Version: libprotoc 3.12.4

**Comment by pzheng1025** [comment]
Please try to install the following dependencies.
apt-get update && apt-get install -y cmake g++ libprotobuf-dev protobuf-compiler

**Comment by genedna** [comment]
@pzheng1025  I already install these libraries, but still had some errors.

**Comment by pzheng1025** [comment]
what is your cmake version?
`cmake --version`

**Comment by pzheng1025** [comment]
Find related discussion [here](https://github.com/tikv/tikv/issues/3748)
