### ISSUE TITLE
Inode number management

### ISSUE THREAD

**Issue by ActivePeter** [datenlord/datenlord#349]
**Is your feature request related to a problem? Please describe.**

Current inode number management is based on local atomic value and communicate with other (only cache server currently)

### There's two problem:

- Different nodes will got same inum because their next_inum_to_alloc are not shared and consensus. Communication to get other's inum is only to cache server, whose next_inum_to_alloc seems never updated.
- Though the first problem is solved, If there's two nodes try to alloc inum for same path file (first create or uncached load), one file will get two different inum.

**Describe the solution you'd like**

### Solution for the first problem

- Add an allocable inum range for node state. when the range reached zero, use etcd lock and etcd state to get next range. Here are the steps:

  - lock with a key, like "inode_number_lock"
  - read the next range begin, like "inode_next_range_begin"
  - add up the range begin like 10000, and store back to etcd
  - release the lock

- When we have to alloc a inum, just make the begin+=1, if it reached end, we do the steps as above.

 ### Solution for the second problem

 One case is create new file

 Another case is load uncached file from s3
 
 The main point is to avoid two requests with same file path, but different inode number

#### Solution one: use a global lock for one path, like "lock"+path

cases:

1. communicate with other nodes, and got inum
2. communicate and found no inum;  lock;  communicate and found no inum;  alloc ino;  unlock
3. communicate and found no inum;  lock;  communicate and found inum;  unlock;
    
#### Solution two: use a global inode number for path, like "inode"+path: inum

 cases:

1. communicate with other nodes, and got inum
2. communicate and found no inum;  try write kv when there's none;  write success;
3. communicate and found no inum;  try write kv when there's none;  write failed and get old;

There are some changes need on metadata.create_node_helper:

- create_node_pre_check // check local cache exist
- // todo alloc inum as above
- only get ino created by self, create and add to cache
- notify others and s3

**Comment by rogercloud** [comment]
One minor question: what about the unused inode number GC for the first solution?

**Comment by ActivePeter** [comment]
> One minor question: what about the unused inode number GC for the first solution?

An unused inode number when found conflict binding, it can be add to a freelist.
The related logic is in fn `inode_get_inum_by_fullpath`.

For the case of a file being evicted from cache, there might be other nodes holding the cache with inode number.
- Solution1 is not to recycle it.
- Solution2 is to persist inode number with file, until it is deleted, which will be talked about later.
- Solution3 is to recycle it when there's no holder, reference count might be expensive for distributed environment.

For the case of after the files be deleted, the inode number can be recycled directly to the freelist. 

I think this job depends on how important the recycle is, if it's ok to lose an unused inode number, we just add it to local freelist. If a node crashed, we just lost some number in freelist. If a node closed normally, we can recycle the freelist when closing.
