### ISSUE TITLE
Excessive Usage of panic! in memfs Metadata Files

### ISSUE THREAD

**Issue by xiaguan** [datenlord/datenlord#376]
I've been observing the use of the `panic!` macro in our memfs metadata files and I believe it is being overused in some scenarios.

While `panic!` is appropriate for situations where the program absolutely cannot continue to operate, there are instances in our code where we could gracefully handle the error and possibly recover instead of panicking.The usage of `panic!` could lead to abrupt termination of the program, making it hard to debug and causing potential downtime in production environments. It's better practice to return Result types which give us an opportunity to handle errors in a controlled manner.
I propose that we revisit these files and refactor the code to minimize the usage of panic!, and where possible, replace it with error handling mechanisms.

**Comment by Reto911** [comment]
All problems mentioned in this issue are resolved, therefore the issue can be closed now.
