### ISSUE TITLE
Remove `lazy_static`

### ISSUE THREAD

**Issue by Reto911** [datenlord/datenlord#475]
With the stabilization of `std::sync::OnceLock` (in 1.70.0), there seems to be better alternatives of `lazy_static`. The crate is not deprecated formally, but is not maintained, and urges users to move to `OnceLock`: https://github.com/rust-lang-nursery/lazy-static.rs/issues/214, https://github.com/rust-lang-nursery/lazy-static.rs/pull/216.

Therefore, I propose that we switch to another solution of static vars:
1. `std::sync::OnceLock`:
```rust
use std::collections::HashMap;
use std::sync::OnceLock;

fn hashmap() -> &'static HashMap<u32, &'static str> {
    static HASHMAP: OnceLock<HashMap<u32, &str>> = OnceLock::new();
    HASHMAP.get_or_init(|| {
        let mut m = HashMap::new();
        m.insert(0, "foo");
        m.insert(1, "bar");
        m.insert(2, "baz");
        m
    })
}

fn main() {
    // First access to `HASHMAP` initializes it
    println!("The entry for `0` is \"{}\".", hashmap().get(&0).unwrap());

    // Any further access to `HASHMAP` just returns the computed value
    println!("The entry for `1` is \"{}\".", hashmap().get(&1).unwrap());
}
```
2. `std::sync::LazyLock`:
Similar to `lazy_static`. **However, this is an unstable feature now.**

```rust
#![feature(lazy_cell)]

use std::collections::HashMap;

use std::sync::LazyLock;

static HASHMAP: LazyLock<HashMap<i32, String>> = LazyLock::new(|| {
    println!("initializing");
    let mut m = HashMap::new();
    m.insert(13, "Spica".to_string());
    m.insert(74, "Hoyten".to_string());
    m
});

fn main() {
    println!("ready");
    std::thread::spawn(|| {
        println!("{:?}", HASHMAP.get(&13));
    }).join().unwrap();
    println!("{:?}", HASHMAP.get(&74));

    // Prints:
    //   ready
    //   initializing
    //   Some("Spica")
    //   Some("Hoyten")
}
```
3. `once_cell::Lazy`
This is the prototype of `std::sync::LazyLock`, whose interfaces are similar to the `std` one.

At present, the use of `lazy_static` is very rare in our project, so it's cheap for us to switch to a new solution:
- [x] `async_fuse::metrics`
- [ ] `csi::util`

**Comment by Reto911** [comment]
I recommend to use the third solution.

**Comment by ActivePeter** [comment]
What's the difference between`OnceLock` and `lazy_static`?

**Comment by Reto911** [comment]
> What's the difference between`OnceLock` and `lazy_static`?

`lazy_static` generates a unique struct for each static variables, while `OnceLock` does not. Besides, `lazy_static` uses macro while `OnceLock` does not.

I do not recommend to use `OnceLock`, because it's still not convenient to use. I recommend `LazyLock`, however `LazyLock` is still unstable, therefore `once_cell::Lazy` will be a better choice.

**Comment by ActivePeter** [comment]
> > What's the difference between`OnceLock` and `lazy_static`?
> 
> `lazy_static` generates a unique struct for each static variables, while `OnceLock` does not. Besides, `lazy_static` uses macro while `OnceLock` does not.
> 
> I do not recommend to use `OnceLock`, because it's still not convenient to use. I recommend `LazyLock`, however `LazyLock` is still unstable, therefore `once_cell::Lazy` will be a better choice.

I think just making the implementation of `lazy_static` replaceable is better.
